### ISSUE TITLE
Strange logging

### ISSUE THREAD

**Issue by hbuerger** [zalando-incubator/hutmann#4]
The following logging seems strange.

`INFO - org.zalando.hutmann.authentication.OAuth2Action - No authorization founder in 'Authorization' header or 'access_token' query parameter. Rejecting access. - 0ms/OAuth2Action.scala:149/JAISn3cdT1uv3CVVGBzzrQ  
INFO - org.zalando.hutmann.authentication.OAuth2Action - Access granted for uid unknown with scopes [] - 0ms/AuthAction.scala:57/JAISn3cdT1uv3CVVGBzzrQ`

**Comment by lenalebt** [comment]
That does not have anything to do with the hutmann itself, but is a following of how you use the library. In your case, you are using `autoReject=false` and then not rejecting anything in your own implementation part.

**Comment by musiKk** [comment]
I guess that's sorted.
