### ISSUE TITLE
Request body is parsed before authentication

### ISSUE THREAD

**Issue by sharma-rohit** [zalando-incubator/hutmann#8]
Scenario:
I had an issue when using multipart form data as request body, The content of the files were streamed from a client which were processed in application and stored in [database](https://github.bus.zalan.do/Cluedo/inventory-movement-comparator/blob/master/app/de/zalando/clue/imc/controllers/ProductInventorySnapshotController.scala#L41).

The problem is even if the request was unauthorized, request body is parsed completely which in turn modifies database state and response code still is 401(Unauthorized)

**Comment by musiKk** [comment]
Released with 0.5.3.
